# zmodload zsh/zprof

# # starship
eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# # Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000

# Antidote
# Download Antidote, if it's not there yet.
[[ -r ${ZDOTDIR:-~}/.antidote/antidote.zsh ]] || git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote

# Start Antidote
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

# init aliases
source ~/.zsh_aliases

# homebrew option
export HOMEBREW_CASK_OPTS=--no-quarantine

# zoxide
eval "$(zoxide init zsh)"

# # Setup fzf
# # ---------
# if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
#   PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
# fi


# # fzf bindings
# # ------------
# source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"

# Mise
eval "$(mise activate zsh --shims)"

# uv
eval "$(uv generate-shell-completion zsh)"


# eval "$(navi widget zsh)"

# Console ninja
# PATH=~/.console-ninja/.bin:$PATH

# PATH=~/Library/Android/sdk/platform-tools:$PATH

# Atuin
eval "$(atuin init zsh)"


# include custom functions
fpath=(${ZDOTDIR:-~}/.zfunc "${fpath[@]}" ) 
for func in ${ZDOTDIR:-~}/.zfunc/*; do
    autoload -Uz ${func:t}
done

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export COREPACK_ENABLE_AUTO_PIN=0

# zprof