# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000

# zsh options
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS

setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

setopt HIST_SAVE_BY_COPY
setopt APPEND_HISTORY

setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY

# Autoload functions.
autoload -Uz zmv
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu

# Utility zsh modules
zmodload -i zsh/complist # completion with highlighting matches
zmodload -i zsh/mathfunc # math funcs built in

# Colors
autoload -U colors && colors
ZSH_HIGHLIGHT_HIGHLIGHTERS=( main brackets )

# Antidote
# Download Antidote, if it's not there yet.
[[ -r ${ZDOTDIR:-~}/.antidote/antidote.zsh ]] || git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote

# Start Antidote
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

# init aliases
source ~/.zsh_aliases

# homebrew option
export HOMEBREW_CASK_OPTS=--no-quarantine

# fpath=($dot_dir/zsh $fpath)

# initialise completions with ZSH's compinit
# autoload -Uz compinit && compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# zoxide
eval "$(zoxide init zsh)"

# Setup fzf
# ---------
if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
fi

# fzf auto-completion
# ---------------
source "/opt/homebrew/opt/fzf/shell/completion.zsh"

# fzf bindings
# ------------
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"


eval "$(mise activate zsh)"
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
