# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Autoload functions.
autoload -Uz zmv

# Define functions and completions.

# aliases
alias tree='lsd --tree'
alias cat='bat'
alias ls="lsd"
alias vim='nvim'

alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias ll='ls -alF'

alias cls='clear'
alias ws='cd ~/workspace'
alias pra='cd ~/workspace/partyround/application'
alias rel='exec zsh'
alias mkd='mkdir'

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu


dot_dir=~/dotfiles
path=(~/bin /opt/homebrew/anaconda3/bin $dot_dir/scripts $path)

# brew
arch=$(uname -m)
if [[ $arch == x86_64* ]]; then
  alias brew='/usr/local/bin/brew'
elif  [[ $arch == arm* ]]; then
  alias brew='/opt/homebrew/bin/brew'
fi

ibrew(){
        arch -x86_64 /usr/local/bin/brew $@
}

nbrew(){
        /opt/homebrew/bin/brew $@
}

which_proc(){
	file $(which $0)
}

# nicer file listings
# checks if exa command is available before setting the aliase
if [ -x "$(command -v exa)" ]; then
    alias ls="exa -1 --classify --group-directories-first"
    alias ll="exa --long --header --classify --icons --group-directories-first --no-permissions"
    alias lp="exa --long --header --classify --icons --group-directories-first"
    alias la="exa -a --long --header --classify --icons --group-directories-first"
    alias lt="exa --tree --long --header --classify --icons --group-directories-first"
    alias t="exa --tree --header --classify --icons --group-directories-first"
fi

# homebrew option
export HOMEBREW_CASK_OPTS=--no-quarantine

# pyenv m1 compatible install
pyenv_safe_install() {
	CFLAGS=-Wno-implicit-function-declaration CPPFLAGS="-I$(brew --prefix openssl@1.1)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl@1.1)/lib -Wno-implicit-function-declaration" pyenv install $@
}

# profile
[ -z "$ZPROF" ] || zprof

# volta
export VOLTA_HOME="$HOME/.volta"
export VOLTA_FEATURE_PNPM=1
export PATH="$VOLTA_HOME/bin:$PATH"
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

